export default {
  yale: {
    id: 'yale',
    name_eng: 'YALE',
    name_kor: '예일',
    logo: '',
    count: 1391,
    isFav: false,
  },
  codegraphy: {
    id: 'codegraphy',
    name_eng: 'CODEGRAPHY',
    name_kor: '코드그라피',
    logo: '',
    count: 341,
    isFav: true,
  },
  lmood: {
    id: 'lmood',
    name_eng: 'LMOOD',
    name_kor: '엘무드',
    logo: '',
    count: 412,
    isFav: false,
  },
  k2: {
    id: 'k2',
    name_eng: 'K2',
    name_kor: '케이투',
    logo: '',
    count: 122,
    isFav: false,
  },
  lee: {
    id: 'lee',
    name_eng: 'LEE',
    name_kor: '리',
    logo: '',
    count: 677,
    isFav: false,
  },
  musinsastandard: {
    id: 'musinsastandard',
    name_eng: 'MUSINSA STANDARD',
    name_kor: '무신사 스탠다드',
    logo: '',
    count: 4721,
    isFav: true,
  },
};
